### ISSUE TITLE
no name of items, only 1 of 5

### ISSUE THREAD

**Issue by dreinn** [EscolarProgramming/NVDARemotePublic#8] opened 2021-05-28 13:38 UTC
Hello,
I'm trying the app on my iphone8, with NVDA 2020.4 on the pc side.
When I connect to pc and press up or down arrow keys on desktop, it doesn't read name of icons or elements, but I listen only 1 of 12, 2 of 12, etc.
So it is quite impossible to browse the computer...
Thank you very much for your efforts!

**Comment by EscolarProgramming** [comment] 2021-05-29 17:56
Hello,
This seams to be a duplicate of https://github.com/EscolarProgramming/NVDARemotePublic/issues/4

Can you please tell me what version of NVDARemote and NVDA you are using?

**Comment by EscolarProgramming** [comment] 2021-05-31 19:01
Hello,
It's fixed in the latest version (1.9), which should be published in the next 15 minutes.

**Closed as completed by EscolarProgramming** 2021-05-31 19:01 UTC
